spring:
  application:
    name: eurka-server
server:
  port: 8761
eureka:
  instance:
    hostname: local.register.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

